/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vue;

import javax.swing.JMenu;
import javax.swing.JMenuBar;
import javax.swing.JMenuItem;

/**
 *
 * @author ZX
 */
public class Principale2 extends javax.swing.JFrame {

    /**
     * Creates new form Principale2
     */
    public Principale2() {
        initComponents();
    }

    public JMenuItem getContenirMI() {
        return ContenirMI;
    }

    public void setContenirMI(JMenuItem ContenirMI) {
        this.ContenirMI = ContenirMI;
    }

    public JMenuItem getDelMiPro() {
        return DelMiPro;
    }

    public void setDelMiPro(JMenuItem DelMiPro) {
        this.DelMiPro = DelMiPro;
    }

    public JMenuItem getNewMiPro() {
        return NewMiPro;
    }

    public void setNewMiPro(JMenuItem NewMiPro) {
        this.NewMiPro = NewMiPro;
    }

    public JMenuItem getUpMiPro() {
        return UpMiPro;
    }

    public void setUpMiPro(JMenuItem UpMiPro) {
        this.UpMiPro = UpMiPro;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuBar1 = new javax.swing.JMenuBar();
        UpdateCat = new javax.swing.JMenu();
        UpMiCat = new javax.swing.JMenuItem();
        NewMiCat = new javax.swing.JMenuItem();
        DelMiCat = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        NewMiPro = new javax.swing.JMenuItem();
        UpMiPro = new javax.swing.JMenuItem();
        DelMiPro = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        UpcmdMi = new javax.swing.JMenuItem();
        NewMICmd = new javax.swing.JMenuItem();
        delCmdMI = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        ContenirMI = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        jMenu1.setText("File");
        jMenuBar2.add(jMenu1);

        jMenu3.setText("Edit");
        jMenuBar2.add(jMenu3);

        jMenuItem2.setText("jMenuItem2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        UpdateCat.setText("Gestion Categorie");

        UpMiCat.setText("Update");
        UpMiCat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpMiCatActionPerformed(evt);
            }
        });
        UpdateCat.add(UpMiCat);

        NewMiCat.setText("Nouveau");
        UpdateCat.add(NewMiCat);

        DelMiCat.setText("Delette");
        UpdateCat.add(DelMiCat);

        jMenuBar1.add(UpdateCat);

        jMenu2.setText("Gestion Produits");

        NewMiPro.setText("Nouveau");
        jMenu2.add(NewMiPro);

        UpMiPro.setText("Update");
        jMenu2.add(UpMiPro);

        DelMiPro.setText("Delette");
        jMenu2.add(DelMiPro);

        jMenuBar1.add(jMenu2);

        jMenu4.setText("Gestion Commandes");

        UpcmdMi.setText("Update");
        jMenu4.add(UpcmdMi);

        NewMICmd.setText("Nouveau");
        NewMICmd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NewMICmdActionPerformed(evt);
            }
        });
        jMenu4.add(NewMICmd);

        delCmdMI.setText("Delette");
        jMenu4.add(delCmdMI);

        jMenuBar1.add(jMenu4);

        jMenu5.setText("Passer Comande");

        ContenirMI.setText("Nouvelle CMD");
        jMenu5.add(ContenirMI);

        jMenuBar1.add(jMenu5);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 677, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 404, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void UpMiCatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpMiCatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UpMiCatActionPerformed

    private void NewMICmdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NewMICmdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NewMICmdActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principale2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principale2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principale2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principale2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principale2().setVisible(true);
            }
        });
    }

    public JMenuItem getNewMICmd() {
        return NewMICmd;
    }

    public void setNewMICmd(JMenuItem NewMICmd) {
        this.NewMICmd = NewMICmd;
    }

    public JMenuItem getUpcmdMi() {
        return UpcmdMi;
    }

    public void setUpcmdMi(JMenuItem UpcmdMi) {
        this.UpcmdMi = UpcmdMi;
    }

    public JMenuItem getDelCmdMI() {
        return delCmdMI;
    }

    public void setDelCmdMI(JMenuItem delCmdMI) {
        this.delCmdMI = delCmdMI;
    }

    public JMenuItem getDelMiCat() {
        return DelMiCat;
    }

    public void setDelMiCat(JMenuItem DelMiCat) {
        this.DelMiCat = DelMiCat;
    }

    public JMenuItem getNewMiCat() {
        return NewMiCat;
    }

    public void setNewMiCat(JMenuItem NewMiCat) {
        this.NewMiCat = NewMiCat;
    }

    public JMenuItem getUpMiCat() {
        return UpMiCat;
    }

    public void setUpMiCat(JMenuItem UpMiCat) {
        this.UpMiCat = UpMiCat;
    }

    public JMenu getjMenu1() {
        return jMenu1;
    }

    public void setjMenu1(JMenu jMenu1) {
        this.jMenu1 = jMenu1;
    }

    public JMenu getjMenu3() {
        return jMenu3;
    }

    public void setjMenu3(JMenu jMenu3) {
        this.jMenu3 = jMenu3;
    }

    public JMenu getjMenu4() {
        return jMenu4;
    }

    public void setjMenu4(JMenu jMenu4) {
        this.jMenu4 = jMenu4;
    }

    public JMenuBar getjMenuBar2() {
        return jMenuBar2;
    }

    public void setjMenuBar2(JMenuBar jMenuBar2) {
        this.jMenuBar2 = jMenuBar2;
    }

    public JMenu getUpdateCat() {
        return UpdateCat;
    }

    public void setUpdateCat(JMenu UpdateCat) {
        this.UpdateCat = UpdateCat;
    }

    public JMenu getjMenu2() {
        return jMenu2;
    }

    public void setjMenu2(JMenu jMenu2) {
        this.jMenu2 = jMenu2;
    }

    public JMenuBar getjMenuBar1() {
        return jMenuBar1;
    }

    public void setjMenuBar1(JMenuBar jMenuBar1) {
        this.jMenuBar1 = jMenuBar1;
    }

    public JMenuItem getjMenuItem1() {
        return jMenuItem1;
    }

    public void setjMenuItem1(JMenuItem jMenuItem1) {
        this.jMenuItem1 = jMenuItem1;
    }

    public JMenuItem getjMenuItem2() {
        return UpMiCat;
    }

    public void setjMenuItem2(JMenuItem jMenuItem2) {
        this.UpMiCat = jMenuItem2;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem ContenirMI;
    private javax.swing.JMenuItem DelMiCat;
    private javax.swing.JMenuItem DelMiPro;
    private javax.swing.JMenuItem NewMICmd;
    private javax.swing.JMenuItem NewMiCat;
    private javax.swing.JMenuItem NewMiPro;
    private javax.swing.JMenuItem UpMiCat;
    private javax.swing.JMenuItem UpMiPro;
    private javax.swing.JMenuItem UpcmdMi;
    private javax.swing.JMenu UpdateCat;
    private javax.swing.JMenuItem delCmdMI;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    // End of variables declaration//GEN-END:variables
}
